input:
  book: 'book.pdf'
  source_language: 'en'
  target_language: 'ru'
output:
  spreadsheet:
    id: '<your Google spreadsheet id>'
    page: '<your Google spreadsheet page>'
    range: 'A2:F'
config:
  frequency: 4
